### ISSUE TITLE
鹿管插件启用 monetary currency key 设置

### ISSUE THREAD

**Issue by manipEgo** [shangxueink/koishi-shangxue-apps#37]
明明插件里已经实现了，为什么函数不调用 config 设定值，还把设置 disable 了呢？

**Comment by shangxueink** [comment]
下个版本改一下


---

不想让用户修改数据库字段

**Comment by shangxueink** [comment]
默认值是deerpipe这样好吗？

还是按照koishi-plugin-checkin一样，使用
```
export const Config: Schema<Config> = Schema.object({
  currency: Schema.string().default('default'),
  reward: Reward,
})
```
currency的默认值设置为`default`比较好呢？

**Comment by manipEgo** [comment]
我觉得设定自己的 currency 是合适的做法，只是现在 monetary 生态里下游调用货币的插件很多并没有好好实现利用 default 以外 currency 的功能。我是在用鹿管配合社区 21 点插件。后者改起来麻烦一点所以（

**Comment by shangxueink** [comment]
好嘛

为了兼容原本的数据，还是默认`deerpipe`好了

---

1.5.3 更新
