### ISSUE TITLE
使用中的一些问题

### ISSUE THREAD

**Issue by Neptune1990** [shangxueink/koishi-shangxue-apps#43]
System:
    OS: Windows 10 10.0.19045
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700

Binaries:
    Node: 20.12.1
    Yarn: 4.0.1

Koishi:
    Core: 4.18.0
    Console: 5.28.4
    Koishi Desktop: 1.1.1

适配器onebot6.7.3

上传图片放大后迟迟不出图，上去看了下似乎没有正确收到图。
![image](https://github.com/user-attachments/assets/dfdee189-c612-4009-b5ee-b9aa4f4ea227)
以及开了会员都令人绝望的放大速度。
![image](https://github.com/user-attachments/assets/db6fd2a3-a2f6-4831-b18e-db2a3af3df73)

**Comment by Neptune1990** [comment]
第一个后续放大成功了，只是显示的问题，但是非常的慢……，插件那边已经超时很久了。

**Comment by shangxueink** [comment]
额，我设定的最大检查时间是1分钟

或许是超过了这个时间吧


---

在QQ平台发送的图可能会被压缩 我建议

如果你的确需要放大高分辨率的图，还是去bigjpg网站比较好

---

本身做这个插件是为了方便白嫖而已（（（

**Comment by Neptune1990** [comment]
![d5d18dcb14db3400e3afea5bf9c66b09](https://github.com/user-attachments/assets/882ab42e-0b0a-4951-9911-ef05573730bb)
emmm，小图放大速度也慢的离谱（上图的320x320给我放大了2分多钟），说实话没啥体验，要是支持SD就好了，不是一个体验等级。

**Comment by shangxueink** [comment]
啊嘞？

我测试的时候，感觉小图还挺快的


这个 不好说，  可能，人家的免费服务就是注重更快吧（（（

付费服务或许更注重放大


---

SD放大啊，我记得插件市场已经有了

但是就是因为sd不是每个人都能有，才有了bigjpg嘛



---

**Comment by Neptune1990** [comment]
我已经是付费了，不得不吐槽这个站，付费了速度慢的离谱……，sd-extra插件市场那个停更很久了，之前也留言了，似乎已经不更新了，还挺喜欢那个插件的。
![5b5fe7a990e9616805401920e328017b](https://github.com/user-attachments/assets/dc16e832-4346-49a0-8fc9-35dfadef0bad)

**Comment by shangxueink** [comment]
这样啊

---

`sd-extra`  是42的插件呢

可能 他太忙了吧

**Comment by Neptune1990** [comment]
已经在论坛里求有偿继续更新了，有兴趣的话可以看下（价格我能承受的话）。
![21af801812d722a7e65a683cbdd33cd6](https://github.com/user-attachments/assets/0d949d20-b751-444f-a097-aecbb04a3a40)

**Comment by shangxueink** [comment]
我更喜欢语音类的（（（

---

有时间我会看看的

AI类的。。。

奶龙识别那个我也有点兴趣
