### ISSUE TITLE
emojihub-bili报错

### ISSUE THREAD

**Issue by Lsoland** [shangxueink/koishi-shangxue-apps#49]
接收到命令后爆出
session Error: Error with request send_group_msg, arg
s: {"group_id":2163017843,"message":[{"type":"image","data":{"file":"file:///
C:/Users/Administrator/Desktop/%E5%8F%B2%E8%AE%B0-%E7%89%B9%E6%B5%93/%E7%BE%A4
u/CD3E8E1AA0DFE85D53692DDC061B5A03.jpg","cache":0}}]}, retcode: 1200
 at _Internal._get (C:\Users\Administrator\AppData
\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-adap
ter-onebot\lib\index.js:119:11)
 at process.processTicksAndRejections (node:interna
l/process/task_queues:95:5)
 at async _Internal.<computed> [as sendGroupMsg]
(C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default
\node_modules\koishi-plugin-adapter-onebot\lib\index.js:162:20)
 at async OneBotMessageEncoder.flush (C:\Users\Admi
nistrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\k
oishi-plugin-adapter-onebot\lib\index.js:763:330)
 at async OneBotMessageEncoder.send (C:\Users\Admin
istrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@s
atorijs\core\lib\index.cjs:627:5)
 at async Proxy.sendMessage (C:\Users\Administrator
\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@satorijs
\core\lib\index.cjs:357:22)
 at async _Command.<anonymous> (C:\Users\Administra
tor\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishiplugin-emojihub-bili\lib\index.js:957:27)
 at async Array.<anonymous> (C:\Users\Administrator
\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs
\core\lib\index.cjs:1083:14)
 at async _Command.execute (C:\Users\Administrator
\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs
\core\lib\index.cjs:1097:22)
 at async C:\Users\Administrator\AppData\Roaming\Ko
ishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:

**Comment by shangxueink** [comment]
code1200 检查你的协议端日志

**Comment by Lsoland** [comment]
> code1200 检查你的协议端日志

找了下LLonebot的日志
2024/11/11 17:54:24 ntqq api timeout IPC_UP_3, ns-ntApi-3, nodeIKernelProfileService/getUserSimpleInfo [ { uids: [ 'u_eEMSk9NMWfi0fnTJvn9dWA' ], force: true } ] 

2024/11/11 17:54:24 [error] (3972287152) | onebot handling incoming messages ntqq api timeout IPC_UP_3, ns-ntApi-3, nodeIKernelProfileService/getUserSimpleInfo, [{"uids":["u_eEMSk9NMWfi0fnTJvn9dWA"],"force":true}]

2024/11/11 17:54:24 ntqq api timeout IPC_UP_3, ns-ntApi-3, nodeIKernelProfileService/getUserSimpleInfo [ { uids: [ 'u_eEMSk9NMWfi0fnTJvn9dWA' ], force: true } ] 

2024/11/11 17:54:24 [error] (3972287152) | satori ntqq api timeout IPC_UP_3, ns-ntApi-3, nodeIKernelProfileService/getUserSimpleInfo, [{"uids":["u_eEMSk9NMWfi0fnTJvn9dWA"],"force":true}]

能告诉下怎么查ws协议端的日志么

**Comment by Lsoland** [comment]
> code1200 检查你的协议端日志

2024/11/11 18:07:53 [info] 最优质的群友(3972287152) | onebot 收到反向 Websocket 消息 { action: 'send_private_msg', params: { user_id: 2721221437, message: [ { type: 'text', data: { text: '1' } } ] }, echo: 14 }

2024/11/11 18:07:54 [info] 最优质的群友(3972287152) | onebot 消息发送 { chatType: 1, peerUid: 'u_eEMSk9NMWfi0fnTJvn9dWA' }

2024/11/11 18:08:02 [info] 最优质的群友(3972287152) | onebot WebSocket 事件上报 ws://127.0.0.1:5140/onebot message.private

2024/11/11 18:08:02 [info] 最优质的群友(3972287152) | onebot 收到反向 Websocket 消息 { action: 'send_private_msg', params: { user_id: 2721221437, message: [ { type: 'image', data: { file: 'file:///C:/Users/Administrator/Desktop/%E5%8F%B2%E8%AE%B0-%E7%89%B9%E6%B5%93/%E7%BE%A4u/QQ20241007-175411.png', cache: 0 } } ] }, echo: 16 }

2024/11/11 18:08:02 [error] 最优质的群友(3972287152) | onebot 发生错误 URIError: URI malformed at decodeURIComponent (<anonymous>) at getPathFromURLWin32 (node:internal/url:1418:14) at Object.fileURLToPath (node:internal/url:1466:35) at uri2local (C:\Users\Administrator\Desktop\LiteLoaderQQNT (1)\plugins\LLOneBot\main\main.cjs:7:1434) at handleOb11RichMedia (C:\Users\Administrator\Desktop\LiteLoaderQQNT (1)\plugins\LLOneBot\main\main.cjs:353:45141) at createSendElements (C:\Users\Administrator\Desktop\LiteLoaderQQNT (1)\plugins\LLOneBot\main\main.cjs:353:42431) at SendPrivateMsg._handle (C:\Users\Administrator\Desktop\LiteLoaderQQNT (1)\plugins\LLOneBot\main\main.cjs:353:59213) at async SendPrivateMsg.websocketHandle (C:\Users\Administrator\Desktop\LiteLoaderQQNT (1)\plugins\LLOneBot\main\main.cjs:353:51585) at async OB11WebSocketReverse.handleAction (C:\Users\Administrator\Desktop\LiteLoaderQQNT (1)\plugins\LLOneBot\main\main.cjs:14:51974)

2024/11/11 18:08:24 开始检查 FFmpeg  

2024/11/11 18:08:24 FFmpeg is not installed or not found in PATH: Error: Cannot find ffmpeg
    at C:\Users\Administrator\Desktop\LiteLoaderQQNT (1)\plugins\LLOneBot\main\main.cjs:12:20214
    at C:\Users\Administrator\Desktop\LiteLoaderQQNT (1)\plugins\LLOneBot\main\main.cjs:12:26671
    at C:\Users\Administrator\Desktop\LiteLoaderQQNT (1)\plugins\LLOneBot\main\main.cjs:12:26639
    at C:\Users\Administrator\Desktop\LiteLoaderQQNT (1)\plugins\LLOneBot\main\main.cjs:9:8069
    at p (C:\Users\Administrator\Desktop\LiteLoaderQQNT (1)\plugins\LLOneBot\main\main.cjs:9:5376)
    at b (C:\Users\Administrator\Desktop\LiteLoaderQQNT (1)\plugins\LLOneBot\main\main.cjs:9:5565)
    at C:\Users\Administrator\Desktop\LiteLoaderQQNT (1)\plugins\LLOneBot\main\main.cjs:9:5682
    at C:\Users\Administrator\Desktop\LiteLoaderQQNT (1)\plugins\LLOneBot\main\main.cjs:9:4441
    at C:\Users\Administrator\Desktop\LiteLoaderQQNT (1)\plugins\LLOneBot\main\main.cjs:9:3350
    at FSReqCallback.oncomplete (node:fs:197:21) 

2024/11/11 18:08:24 查询 LLOneBot 错误信息 没有找到 FFmpeg, 音频只能发送 WAV 和 SILK, 视频尺寸可能异常 

2024/11/11 18:08:27 LLOneBot latest version 4.1.4 
请问是这个么

**Comment by shangxueink** [comment]
> 2024/11/11 18:08:02 [error] 最优质的群友(3972287152) | onebot 发生错误 URIError: URI malformed at decodeURIComponent () at getPathFromURLWin32 (node:internal/url:1418:14) at Object.fileURLToPath (node:internal/url:1466:35) at uri2local (C:\Users\Administrator\Desktop\LiteLoaderQQNT (1)\plugins\LLOneBot\main\main.cjs:7:1434) at handleOb11RichMedia (C:\Users\Administrator\Desktop\LiteLoaderQQNT (1)\plugins\LLOneBot\main\main.cjs:353:45141) at createSendElements (C:\Users\Administrator\Desktop\LiteLoaderQQNT (1)\plugins\LLOneBot\main\main.cjs:353:42431) at SendPrivateMsg._handle (C:\Users\Administrator\Desktop\LiteLoaderQQNT (1)\plugins\LLOneBot\main\main.cjs:353:59213) at async SendPrivateMsg.websocketHandle (C:\Users\Administrator\Desktop\LiteLoaderQQNT (1)\plugins\LLOneBot\main\main.cjs:353:51585) at async OB11WebSocketReverse.handleAction (C:\Users\Administrator\Desktop\LiteLoaderQQNT (1)\plugins\LLOneBot\main\main.cjs:14:51974)
 
 
 你换个文件夹存放吧
文件路径中的特殊字符未正确编码，导致 decodeURIComponent 解析失败

**Comment by Lsoland** [comment]
> 另外日志还提示你没有ffmpeg环境
> 
> 发送音频或者视频可能有问题

已经解决了,中文路径的问题
