### ISSUE TITLE
关于impartpro插件存在的一些bug反馈

### ISSUE THREAD

**Issue by HuaJi114** [shangxueink/koishi-shangxue-apps#51]
大佬开发的牛牛大作战非常好玩，不过我们在游玩过程中遇到了一些问题，故来此给大佬反馈一下：

1、关于群内排行榜和跨群排行榜开关的问题：目前我们在游玩中了解到，如果关闭排行榜的跨群开关，排行榜上的名称使用的是用户在群内的昵称，这没有问题，但是当一个用户在多个群进行游玩时，会出现A群的排行榜显示的是该用户在B群的昵称，可否修改成在哪个群触发排行榜，就显示该用户在该群的昵称？；

2、关于群内排行榜和跨群排行榜开关的问题：当开启排行榜的跨群开关后，会以用户生成牛牛的群昵称为排行榜昵称，这样在多个群游玩时容易不知道谁是谁，所以建议在开启排行榜的跨群开关后，排行榜上的名称可以显示为用户QQ的真实昵称而非群内昵称；

3、目前开导命令和决斗命令是共享cd的，可否将各个命令的cd分开计算？

4、目前保养命令无论用户的monetary余额有多少，都会显示余额不足，不知道是否为bug？

最后，再次感谢大佬开发这么好玩的插件，一定要继续塔塔开口牙！

**Comment by shangxueink** [comment]
> A群的排行榜显示的是该用户在B群的昵称，可否修改成在哪个群触发排行榜，就显示该用户在该群的昵称？
这个是因为我预期是与deer pipe插件一致，进行一次「开导」就会判断更新一次数据库，自然也包括用户的名称。所以最后在哪个群触发的，排行榜显示到就是该用户在哪个群的群名称。

现在不会自动更新该用户的名称到对应群的群名称吗？

---

> 排行榜上的名称可以显示为用户QQ的真实昵称而非群内昵称
这个……，我用的是session.username，获取到的只能是该用户在群组的群名称，适配器也不支持获取QQ号对应名称吧？ 你在什么插件见过这样的功能吗？


---

> 目前开导命令和决斗命令是共享cd的，可否将各个命令的cd分开计算？

这个可以做

> 保养命令无论用户的monetary余额有多少，都会显示余额不足，不知道是否为bug

这个我测试过，功能是正常的，你有没有具体日志，注意看一下货币数据库的字段，本插件默认的monetary字段是impartpro，与monetary默认的default不一致。

提供一下复现条件与本插件配置项，或者日志报错
