### ISSUE TITLE
deerpipe不能获取用户群昵称

### ISSUE THREAD

**Issue by MOZac-hash** [shangxueink/koishi-shangxue-apps#56]
![S90XWXA9X`8R0P982 WV@ A](https://github.com/user-attachments/assets/879349b4-08c4-4b67-b71d-333589706c40)
如图，deerpipe插件无法准确获取用户昵称
![$8BAMVT( DCZU7UBKH%M@IU](https://github.com/user-attachments/assets/23e4e4fc-4c77-4d55-8792-94687a3ce72e)

**Comment by shangxueink** [comment]
可是官方机器人他就是不能

**Comment by shangxueink** [comment]
本插件也不支持官方bot啊……

**Comment by shangxueink** [comment]
最新版本的排行榜支持

用户昵称可以通过 callme 插件自定义昵称

在未指定 callme 插件的名称的时候，默认使用 适配器的username，或者userid
