### ISSUE TITLE
impartpro【开始银趴\结束银趴】指令有bug

### ISSUE THREAD

**Issue by MOZac-hash** [shangxueink/koishi-shangxue-apps#61]
#### 问题截图
![Screenshot_20241203_190717_com tencent mobileqq](https://github.com/user-attachments/assets/aea343b2-92c6-4f0a-ae91-7e736f44e543)
![Screenshot_20241203_190711_com tencent mobileqq](https://github.com/user-attachments/assets/2b33643e-716a-4e9e-81ee-b18d7fda3d14)

#### 问题描述
通过【开始银趴】启用牛牛大作战后，无法使用【结束银趴】关闭

**Comment by shangxueink** [comment]
这不是我的插件

**Comment by shangxueink** [comment]
请你提供 impart-pro的指令别名截图
