### ISSUE TITLE
deer-pipe 能否为 [鹿 @其他人] 添加每日次数上限，让每个用户每日只能帮 限定人数 鹿

### ISSUE THREAD

**Issue by yunling520** [shangxueink/koishi-shangxue-apps#62]
![image](https://github.com/user-attachments/assets/af93f924-da14-4449-b899-a2980fa4b6df)
如题，鹿自己可以配置上限，但鹿他人没上限
所以有群友为了货币把全体都鹿了个遍......

**Comment by shangxueink** [comment]
1.9.0更新
