### ISSUE TITLE
deerpipe插件功能指令异常求助

### ISSUE THREAD

**Issue by GSRealms** [shangxueink/koishi-shangxue-apps#63]
带锁功能遇到错误
![89B301BE6D6319E62A35C321AFCD0759](https://github.com/user-attachments/assets/68a7bdc0-da01-45b0-afd0-82f54d8c686d)

**Comment by shangxueink** [comment]
上次改后 忘记加回去了

---


更新插件至1.9.4版本，并且恢复此配置项为默认值
```
货币平衡设置
涉及游戏平衡，谨慎修改
【获取硬币】本插件指令的货币变动
```

然后重载插件

![image](https://github.com/user-attachments/assets/dae8459f-a913-4330-ab81-14bcf3b6b2da)
