### ISSUE TITLE
关于koishi-plugin-image-save-path的优化改进需求

### ISSUE THREAD

**Issue by GSRealms** [shangxueink/koishi-shangxue-apps#66]
请问koishi-plugin-image-save-path这个插件能够否添加一个精简的指令，
使其 实现 在默认指定目录下创建文件夹并将图片保存进去，
例如：当我回复图片消息并使用指令“添加 wyy”，能够自动的在E:\Bot\pictures目录下创建wyy文件夹并将图片保存在E:\Bot\pictures\wyy目录下，便于之后使用“来只 wyy”指令实现bot发指定文件夹中的表情包

**Comment by shangxueink** [comment]
更新 1.1.0 版本

并且开启 配置项
```
imageSaveMode: Schema.boolean().description("开启后，默认选择了第一个路径，可以缺省路径参数<br>当然也支持输入路径参数<br>[此配置项效果图](https://i0.hdslb.com/bfs/article/1d34ae45de7e3c875eec0caee5444149312276085.png)").default(false),
```

---

> 使用“来只 wyy”指令实现bot发指定文件夹中的表情包

这个可以使用 emojihub 插件实现

**Comment by GSRealms** [comment]
请问koishi的插件市场上1.1.0版本什么时候上架捏

**Comment by shangxueink** [comment]
> 请问koishi的插件市场上1.1.0版本什么时候上架捏

插件一直在，

版本的话，这与npm源有关

我在 npm的镜像源已经看到了 1.1.0 版本

![image](https://github.com/user-attachments/assets/038b5062-1e24-492e-bb18-f2f5bec2dd0b)

---


你需要在koishi 活动栏的 【依赖管理】 右上角 刷新 并且更新 image-save-path 插件

**Comment by GSRealms** [comment]
okk，另外再问下emojihub如何实现可变的指令，比如：除了“来只 wyy”，还有“来只 zero”之类的这种，只要在指定目录上有zero的文件夹就可以”来只 zero“

**Comment by shangxueink** [comment]
建议分成两个指令

![image](https://github.com/user-attachments/assets/a457e4e2-875f-4f2f-91d5-269e07eadda1)

--

保存图片插件可以这样


![image](https://github.com/user-attachments/assets/9722c415-0759-445c-b08a-bb652c0f8f8c)

**Comment by shangxueink** [comment]
如果你要把【wyy】和【zero】做成参数，而且用emojihub 实现的话，

那你在保存的时候就必须让他们在同一个文件夹，并且要在文件命名上有特征区别

---

如果你要把【wyy】和【zero】做成参数

你也可以通过其他插件实现 

![image](https://github.com/user-attachments/assets/f95f6f64-3c00-439e-a66c-da58b97d0b2e)

**Comment by GSRealms** [comment]
okk，在同一文件夹中保存的话可以用”来只“指令，然后后面跟上图片名称，也能实现这个效果，然后把递归搜索关闭，就可以实现随机wyy图片输出

**Comment by GSRealms** [comment]
我想满足的需求基本实现了，谢谢你
