### ISSUE TITLE
emojihub自动撤回偶尔失效

### ISSUE THREAD

**Issue by GSRealms** [shangxueink/koishi-shangxue-apps#67]
emoji插件的自动定时撤回偶尔会失效
![image](https://github.com/user-attachments/assets/f74fcd02-201a-4027-968e-ca668e4a909b)

**Comment by GSRealms** [comment]
![image](https://github.com/user-attachments/assets/b9f387f6-1080-4818-bc5c-b851efe40ee3)

**Comment by shangxueink** [comment]
请提供更详细的配置项和具体复现步骤

---

我看记录到message_id是0，并且还有onebot的超时报错

可能是因为图片没有发出去导致的

**Comment by GSRealms** [comment]
![image](https://github.com/user-attachments/assets/5a6ed84e-442e-4f61-a5af-422ab2ecffd4)

**Comment by GSRealms** [comment]
这个图片是我把撤回时间改成1s，然后反复发送得到的情况，中间那条没有被撤回

**Comment by shangxueink** [comment]
> 撤回时间改成1s，然后反复发送得到的情况，中间那条没有被撤回

在我这里暂时复现不出来

---

1s太短了，吧，可能协议端处理起来会出问题

---

如果有问题

那大概率是协议端的问题

---

我看到你



> ![image](https://private-user-images.githubusercontent.com/135619452/393119529-b9f387f6-1080-4818-bc5c-b851efe40ee3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NjYyODksIm5iZiI6MTczMzQ2NTk4OSwicGF0aCI6Ii8xMzU2MTk0NTIvMzkzMTE5NTI5LWI5ZjM4N2Y2LTEwODAtNDgxOC1iYzVjLWI4NTFlZmU0MGVlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQwNjE5NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNGNlYmEwY2UxMWI2NGYxOWNhNTI3ZGFlMTgzYjAyZjU2MjUxNGQyNzZiNjRjNzdkODliOWMxYTk2NWQ5OTRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5mZrjwOV_wdiFS_OWCjwP5szLDe4BTGhWeiPXDITDtA)

我看到你这里有 adapter-onebot 的超时发送的日志 所以可能是这样的
```
 adapter-onebot 给协议端请求，某些原因导致了  adapter-onebot 认为协议端发送超时了，所以日志报错了【timeout】

但是实际上协议端又发出去了

导致 这一条【koishi认为没发出去但是实际发出去了】的图片 在 koishi 侧 并不能找到对应的 message_id 

所以导致无法撤回

```

**Comment by GSRealms** [comment]
之前60s撤回也会有这样的情况，就是有些消息能撤回有些撤回失败

**Comment by shangxueink** [comment]
> 有些消息能撤回有些撤回失败

不好稳定复现，就不好确定问题在哪

但是大概率是关于 onebot 实现 侧的问题


---

**Comment by GSRealms** [comment]
嗯嗯，好的，那我该找onebot提交issue对吧

**Comment by shangxueink** [comment]
> 那我该找onebot提交issue对吧

不对哦

你应该先找协议端日志

然后找到对应的报错

给你的协议端提issue

---


因为 adapter-onebot 报错内容表示

是请求超时了

所以的确是正确请求了，但是响应出问题了

**Comment by shangxueink** [comment]
> 比如nc、llob、icqq... 你的onebot实现

所以你的协议端是什么哦

**Comment by GSRealms** [comment]
是指bot对接的平台吗，协议端。。我是qq上的LiteloaderQQNT上的napcatqq插件

**Comment by shangxueink** [comment]
> LiteloaderQQNT上的napcatqq插件

那你需要先找到napcat的日志


如果能找到【为什么koishi尝试发图片出去 但是超时了 实际上却还是发出去了】的日志

就好了

---

**Comment by GSRealms** [comment]
嗯嗯好的，谢谢您
