### ISSUE TITLE
image-save-path 文件夹名称备注bug

### ISSUE THREAD

**Issue by shangxueink** [shangxueink/koishi-shangxue-apps#69]
目前发现把文件夹名称 备注为单个纯数字的时候会出现bug

---

**Comment by shangxueink** [comment]
https://github.com/shangxueink/koishi-shangxue-apps/issues/70


---


再加个单选配置项

1.「保存图片 图片重命名 文件夹备注」
2.「保存图片 文件夹备注 图片重命名」

3.「保存图片 图片重命名」（仅存到第一个文件夹里）

4.「保存图片 文件夹备注」（自动图片重命名:1.使用配置项固定文件名 2.使用安全的「2024-12-11.png」这样的）

5.「保存图片」（以自动重命名保存到第一关文件夹路径）

**Comment by rainpenber** [comment]
从 #70 过来的，支持这个设计

**Comment by shangxueink** [comment]
https://github.com/shangxueink/koishi-shangxue-apps/issues/70#issuecomment-2536524723

一并修了
