### ISSUE TITLE
[Feature Request]image-save-path 自动命名？

### ISSUE THREAD

**Issue by rainpenber** [shangxueink/koishi-shangxue-apps#70]
## 需求描述
从1.0.1更新到1.1.2后功能变化，导致我个人的原有配置失效

旧版本下：
我设置savePaths中，备注名1对应目录`D:\A\`
**指令【保存图片 1】 > 保存图片到文件夹【D:\A\】中，并自动取名为当前时间.png**

在不同的群里，我只需要设置不同的指令别名，例如
设置指令别名 `保存猫猫` 等效于 `保存图片 1` ，这样实现了自动保存这张图

现在更新到1.1.2后，由于指令的第一个参数为图片名称，所以以上的功能直接失效了
`保存图片 1 `现在是指定了文件名为`1.png`

## 诉求
能否修改指令，能自动生成一个文件名
举例1：参数设置为 --auto-name
保存图片 --auto-name 表情包A  效果为保存到备注名为【表情包A】对应的目录，并自动生成一个文件名
举例2：使用模板名称，例如{autoname} 或者 {date}
保存图片 {date} 表情包A 效果为保存到备注名为【表情包A】对应的目录，并自动以当前日期作为文件名

## 诉求理由
image-save-path在聊天中经常用来保存特定表情包，而保存的时候一般不会需要给表情包命名，个人意见认为这个频率比较低，如果能自动生成文件名，会比较方便

**Comment by shangxueink** [comment]
很好的建议，

下个版本更新适配，可以选择输入参数的格式与交互方式。

**Comment by shangxueink** [comment]
目前同时有几种用户需求

有的用户喜欢 先输入图片重命名，再输入文件夹备注名称

也有用户喜欢直接指定到文件夹即可，不在乎文件名

---

我打算下个版本作为一个单选的配置项，允许指令拥有多种交互方式模式

同时实现以上所有的输入适配

**Comment by shangxueink** [comment]
> 举例1：参数设置为 --auto-name
保存图片 --auto-name 表情包A 效果为保存到备注名为【表情包A】对应的目录，并自动生成一个文件名


这个是什么效果

可以用实际聊天环境演示一下吗，没怎么看懂



看起来似乎是对「不指定文件名时自动重命名」的默认文件名

**Comment by rainpenber** [comment]
> > 举例1：参数设置为 --auto-name
> > 保存图片 --auto-name 表情包A 效果为保存到备注名为【表情包A】对应的目录，并自动生成一个文件名
> 
> 这个是什么效果
> 
> 可以用实际聊天环境演示一下吗，没怎么看懂
> 
> 看起来似乎是对「不指定文件名时自动重命名」的默认文件名

这个案例中，我个人的想法是，保持您设计的参数的位置，即第一个参数为图片名，第二个参数为路径，etc，
但是如果图片名填写为一个特定的内容，则触发自动生成名称：
```bash
保存图片  --auto D:\A\
```
或者
```bash
保存图片 自动命名 D:\A\
```
------
如果是问关于这个写法的解释，`--auto-name` 是一个完整的参数，前面两个`-`意思是避免程序将第一个`-`之后的字母识别为其他参数，表明这个参数不是一个字母，而是一组单词，算是一种行业惯例？

看了您对插件参数的设计，我理解是您是固定了参数的位置，第一个参数是XXX，第二个参数是XXX
而这种由字母指定参数的方式，可以任意排列参数的顺序，例如：

> 假设saveimg是指令名称
> -n 是指定名称，-p 是指定路径
> --name 是-n的全称， --path 是-p的全称
```bash
saveimg -n 1.png -p "D:\A\"

saveimg --name 1.png --path "D:\A\"

saveimg -p "D:\A\" - n  1.png
```
这三个命令等效

不过弊端也很明显，需要输入额外的英文字母，给使用带来不便，所以还是看您希望如何设计

------
如果有表述不清，为此表示抱歉！

**Comment by shangxueink** [comment]
> 不过弊端也很明显，需要输入额外的英文字母

就是这个问题
虽然使用指令的选项，可以避免输入参数顺序的问题

但是额外的字母，尤其是对于初上手的用户，这不好理解。对于快速保存表情包也不是很方便啊，存个表情包还要一堆参数，还不如QQ自带的「存表情」呢

---

我目前是打算这样

https://github.com/shangxueink/koishi-shangxue-apps/issues/69

加个这样的单选项配置项，来兼容所有的情况

选项的话，可以考虑参数全都做进选项里去

**Comment by shangxueink** [comment]
1.2.0 更新解决

---

## 🌟 新版本

- **移除 `imageSaveMode` 配置项**，简化功能逻辑。
- **新增交互模式配置**：通过 `Interaction_mode` 选择不同的指令参数顺序，满足多样化需求。

---

![image](https://github.com/user-attachments/assets/f7ccce44-666d-4158-8db9-3c0770c25930)
