### ISSUE TITLE
image-save-path使用保存图片指令，保存图片时出错日志报错Bad Request

### ISSUE THREAD

**Issue by xsjh** [shangxueink/koishi-shangxue-apps#73]
![image](https://github.com/user-attachments/assets/09f81727-23ca-4d63-a251-91d68c2db2db)
打开日志调试模式后，如上图所示
已知：
1、koishi对该文件夹有读写权限，使用local-pic-sleter发送图片是成功的，使用其它插件存图也是成功的
2、使用的interaction_mode是4，
savePaths如下图所示
  
![image](https://github.com/user-attachments/assets/11921520-2d88-4636-8fc4-d343b3caa2dd)

请问是否是网络原因，我该如何排查？
正常环境和魔法环境我都重启后尝试过，皆报错Bad Request
谢谢作者！
附图：
![image](https://github.com/user-attachments/assets/ccaf463c-baa6-4fab-b296-1d934b3b61ec)

**Comment by shangxueink** [comment]
> ![image](https://private-user-images.githubusercontent.com/166027220/398303259-09f81727-23ca-4d63-a251-91d68c2db2db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMTk0NTYsIm5iZiI6MTczNTAxOTE1NiwicGF0aCI6Ii8xNjYwMjcyMjAvMzk4MzAzMjU5LTA5ZjgxNzI3LTIzY2EtNGQ2My1hMjUxLTkxZDY4YzJkYjJkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNFQwNTQ1NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lM2Q2MWE5NDdiMmM1ZWZlYTg3NThiMjNmZWM5YTdjOGYwYTVhNTlkYmQyN2YwMWY1Yzc1YjM0NzZmYTJkOTU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5G3WGgunM9YRcQeLwA5yPMbi4bVomAbjJjvpg3M04Wc) 


对于这个日志里面的图片链接，你看看是不是确切可以有效访问的

看起来插件似乎是提取到了图片的链接

而我又实在复现不出来这样的 `Bad Request`  的情况

保存图片的函数逻辑，是使用 `ctx.http.get`  对图片链接进行访问的，

---


建议 尝试先试试看换一个onebot实现，或者换一个平台尝试

**Comment by xsjh** [comment]
感谢作者帮助排查，回退qqnt版本后，问题已解决
回退至9.9.16-29456
