### ISSUE TITLE
b站近期出现的新短链格式,bilibili-videolink-analysis插件无法解析

### ISSUE THREAD

**Issue by Readedd** [shangxueink/koishi-shangxue-apps#76]
bilibili-videolink-analysis插件
前缀格式如下http://bili2233.cn/xxxxx

**Comment by shangxueink** [comment]
后续更新加上

**Comment by shangxueink** [comment]
https://github.com/shangxueink/koishi-shangxue-apps/actions/runs/12562292807/job/35022519075

已经更新了呢

实测可用

![image](https://github.com/user-attachments/assets/d9bc4c42-616a-472f-b7fa-35967fe15fac)
